### ISSUE TITLE
mhs_arc_unpack.py fails due to a syntax error

### ISSUE THREAD

**Issue by Chew** [LITTOMA/Archive_Tools#1]
```bash
$ python3 arch.py 
  File "arch.py", line 5
    format_table = {2069149184L: 'atd',
                              ^
SyntaxError: invalid syntax
```

so like yikes. I'm using Python 3.

**Comment by Chew** [comment]
I feel like I'm about 10 years late to extracting .arcs, I just want some Super Mario Galaxy sound effects tbh

**Comment by LITTOMA** [comment]
The script was written in Python 2. And it supports  arc format only for Monster Hunter 3DS series. Nintendo's archive format is quite different from this.

**Comment by Chew** [comment]
Alright, is there any .arc unarchivers out there or do I even need one for what I'm trying to get?

**Comment by LITTOMA** [comment]
> Alright, is there any .arc unarchivers out there or do I even need one for what I'm trying to get?

You can upload the arc file here. Let me take a look.

**Comment by Chew** [comment]
I've discovered the sound effects to be in a .szc and .aw files, how can I open those up? These are probably beyond the issue but hey

**Comment by LITTOMA** [comment]
Right, .szc or .aw are beyond the issue.
